package com.example.agorademo.utils

const val USER_ID_1="007eJxTYFCUVzj6M2Tdmkfp9UF1Jh6SXxbk6mmq3b2aZh3lWrWvv12BwdAy2cIizdLMwjw1xcTYIMUiyTI5Mdk0OTkxNdEwJS2FkaUruSGQkWFdHTMTIwMrAyMQgvgqDIYmxmlpSUkGuuZGJpa6hoapKbqJKYbmumZJyYnmiSYpBslGxgAEniZp"
const val USER_ID_2="007eJxTYGg+ydctpdXFsC3Fc+F69xOxc2XvVV663hLQqN666Of9G4kKDIaWyRYWaZZmFuapKSbGBikWSZbJicmmycmJqYmGKWkpLBN6kxsCGRk2HAxiYWRgZWAEQhBfhcHC1CjJ2CzFQNfcyChF19AwNUXX0tjcQjfV0NgkKTXZONnc3AQAzNsocg=="
const val USER_ID_3="007eJxTYGg44zc1mWeme/HZL1ZNXCcNM65kbD9mox/+f7tKvcP6V3oKDIaWyRYWaZZmFuapKSbGBikWSZbJicmmycmJqYmGKWkpEpN7kxsCGRlmyIcyMzKwMjACIYivwmCWaJSSlGZooGtuZJKka2iYmqKbZGZsoJuYlJhkYpRsYW6SagQAl+Qn6A=="
const val KEY_LOGIN="KEY_LOGIN"
const val PARAM_RECEIVER_ID="PARAM_RECEIVER_ID"