package com.example.agorademo.utils

const val USER_ID_1="007eJxTYFAVf7vHacNOgUOel1+dfSiw3nMl8yIFtpclfDtFjxrYe/ApMBhaJltYpFmaWZinppgYG6RYJFkmJyabJicnpiYapqSl/P/RltwQyMgg//kbCyMDKwMjEIL4KgyJZsmWRqZmBrrmBuYWuoaGqSm6SQYpZroGhqnJKSkmSaaGKakAjCooqQ=="
const val USER_ID_2="007eJxTYOjLvP0ziVWcNab6/XSbTyfMJrfaO2l/VDL5G7p2a1Hg1esKDIaWyRYWaZZmFuapKSbGBikWSZbJicmmycmJqYmGKWkp/j/bkhsCGRleim1lYGRgBWJGBhBfhSE10dQ00cDMQNfcwNxC19AwNUU3McnIUtcoydLEIsnYyNLQzAwA7cAomw=="
const val KEY_LOGIN="KEY_LOGIN"